### ISSUE TITLE
issue with mappings function

### ISSUE THREAD

**Issue by olhakholod** [ayushnoori/metapaths#1]
Hello!

I'm using this vignette - https://www.ayushnoori.com/metapaths/articles/biokg-demo.html - and it produces the error message while running the following code in R:

```
mappings = mappings %>% copy() %>%
  setnames(c("ent idx", "ent name"), c("Index", "Name")) %>%
  setcolorder("Type") %>%
  .[, Label := paste(Type, Index, sep = "_")]

Error in setnames(., c("ent idx", "ent name"), c("Index", "Name")) : 
  Items of 'old' not found in column names: [ent idx, ent name]. Consider skip_absent=TRUE.
```

I followed the first part of tutorial, where I outputted edge_index.json file into inst/extdata folders. Is there an issue with this file?

Thank you!
Olha

**Comment by ayushnoori** [comment]
Hi Olha, thanks for raising this issue. I believe there may be an issue with your mapping files. The OGB-provided files you need are: `disease_entidx2name.csv`, `drug_entidx2name.csv`, `function_entidx2name.csv`, `protein_entidx2name.csv`, and `sideeffect_entidx2name.csv`. In the vignette, we use the May 2020 versions of these files.

When I load these files, the first five rows look like this:

<img width="256" alt="image" src="https://github.com/ayushnoori/metapaths/assets/43010710/46d0e0d4-73e8-4407-ba60-0c4e67b09eae">


I used the following code to load the files (copied from the [vignette](https://www.ayushnoori.com/metapaths/articles/biokg-demo.html)):

```
mapping_dir = "inst/extdata/biokg_mappings"

read_mapping = function(mapping_path) {
  mapping = fread(file.path(mapping_dir, mapping_path))
  mapping[, Type := strsplit(mapping_path, "_")[[1]][1]]
  return(mapping)
}

mappings = list.files(mapping_dir) %>%
  .[grepl("entidx2name", .)] %>%
  map_dfr(read_mapping)
```

In case your mapping files are different,  please find the May 2020 versions of the required files below. 

* [`disease_entidx2name.csv`](https://github.com/ayushnoori/metapaths/files/13803729/disease_entidx2name.csv)
* [`drug_entidx2name.csv`](https://github.com/ayushnoori/metapaths/files/13803730/drug_entidx2name.csv)
* [`function_entidx2name.csv`](https://github.com/ayushnoori/metapaths/files/13803731/function_entidx2name.csv)
* [`protein_entidx2name.csv`](https://github.com/ayushnoori/metapaths/files/13803732/protein_entidx2name.csv)
* [`sideeffect_entidx2name.csv`](https://github.com/ayushnoori/metapaths/files/13803734/sideeffect_entidx2name.csv)

I hope this resolves your error. If not, please feel free to reopen this issue. Thanks and happy new year!
